### ISSUE TITLE
Tag `v1` is gone

### ISSUE THREAD

**Issue by palloberg** [someimportantcompany/github-actions-slack-message#21]
The tag `v1` seems to be missing and the suggested usage is failing:
```
Error: Unable to resolve action `someimportantcompany/github-actions-slack-message@v1`, unable to find version `v1`
```

when doing 
```
      - uses: someimportantcompany/github-actions-slack-message@v1
        with:
         channel: ${{ env.SLACK_CHANNEL }}
         bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
         text: Firing a bot-token message
```
