### ISSUE TITLE
Not supporting enterprise server

### ISSUE THREAD

**Issue by mnourifar** [someimportantcompany/github-actions-slack-message#6]
The hostname github.com appears to be hard-coded into the links for the Actions URL and Commit hash, making the action unsuitable for users on GitHub Enterprise Server where the host is not github.com. The GITHUB_SERVER_URL environment variable should be used instead (see https://docs.github.com/en/actions/reference/environment-variables)

**Comment by jdrydn** [comment]
Hey @mnourifar, thanks for the feedback! Totally agree with you, `GITHUB_SERVER_URL` would be a better fit here - I personally am not a GitHub Enterprise user so I'd miss this!

https://github.com/someimportantcompany/github-actions-slack-message/blob/2637ce2fdb498884618ddfb03098519cd933f3cc/index.js#L41-L58

Assuming you are a GitHub Enterprise user, can you confirm if the following URLs are available, and if not which URL (if applicable) is appropriate:
- [ ] Repository home `${GITHUB_SERVER_URL}/${org}/${repo}`
- [ ] Repository tree `${GITHUB_SERVER_URL}/${org}/${repo}/tree/${branch}`
- [ ] Commit checks `${GITHUB_SERVER_URL}/${org}/${repo}/commit/${sha1}/checks`
- [ ] User profile `${GITHUB_SERVER_URL}/${username}`
- [ ] User avatar `${GITHUB_SERVER_URL}/${username}.png`

I'm happy to then modify this action to account for Enterprise setups, and if a given URL in the above list is missing I'll just omit that link.

Thanks 👋

**Comment by mnourifar** [comment]
Hi again and thanks for your support and nice slack action!

Yeah, I checked and all the URLs are resolvable after switching the base URL.
I just see that the avatar URL is redirected to `https://avatars.${GITHUB_SERVER_URL}/u/1013` which is fine I guess.

Looking forward to using the new version of this!

**Comment by jdrydn** [comment]
@mnourifar `v1` has been updated to support environment variables, including `GITHUB_SERVER_URL`. Any issues please let me know!

**Comment by mnourifar** [comment]
Yeah, it works nicely now!

I as well wanted to do some output formatting and was unsure how to do it, there is a part of the Readme.md which says look below for formatting but I don't see anything there. is it something that you can update as well? or share a link?

**Comment by jdrydn** [comment]
@mnourifar Excellent point - I've updated the documentation to include a link to [Slack formatting documentation](https://api.slack.com/reference/surfaces/formatting#basics) in the README.

**Comment by mnourifar** [comment]
Sorry to bug you here, so far everything works fine and smooth. The only thing I haven't figured yet is why I cannot pass print my env variables to be passed as messages to slack.
```
      - uses: someimportantcompany/github-actions-slack-message@v1
        env:
          sha7: ${ GITHUB_SHA::7 }
        with:
          webhook-url: ${{ secrets.SLACK_URL }}
          channel: actions-test
          text: "Print step output: \n ${{ steps.image-diff.outputs.imagediff }} \n Print Sha: $sha7"
          color: success
 ```
 So in the above example the step output is correctly passed but not the $sha7 env variable. am I doing sth wrong here? or how the text part is processed? just need to shed some light...
